// ============================================================
// API ENDPOINTS
// src/shared/services/api/endpoints.ts
// ============================================================

const BASE = import.meta.env.VITE_API_URL ?? 'http://localhost:5000/api/v1';

export const ENDPOINTS = {
  auth: {
    login:          BASE + '/auth/login',
    register:      BASE + '/auth/register',
    logout:         BASE + '/auth/logout',
    refresh:        BASE + '/auth/refresh',
    forgotPassword: BASE + '/auth/forgot-password',
    resetPassword:  BASE + '/auth/reset-password',
    me:             BASE + '/auth/me',
    mfa:            BASE + '/auth/mfa/verify',
  },
  products: {
    list:        BASE + '/products',
    create:      BASE + '/products',
    detail:      (id: string) => BASE + '/products/' + id,
    update:      (id: string) => BASE + '/products/' + id,
    delete:      (id: string) => BASE + '/products/' + id,
    bulkDelete:  BASE + '/products/bulk-delete',
    export:      BASE + '/products/export',
    import:      BASE + '/products/import',
    uploadImage: (id: string) => BASE + '/products/' + id + '/images',
  },
  categories: {
    list:          BASE + '/categories',
    create:        BASE + '/categories',
    detail:        (id: string) => BASE + '/categories/' + id,
    update:        (id: string) => BASE + '/categories/' + id,
    delete:        (id: string) => BASE + '/categories/' + id,
    uploadImage:   (id: string) => BASE + '/categories/' + id + '/image',
  },
  orders: {
    list:       BASE + '/orders',
    create:     BASE + '/orders',
    detail:     (id: string) => BASE + '/orders/' + id,
    update:     (id: string) => BASE + '/orders/' + id,
    delete:     (id: string) => BASE + '/orders/' + id,
    transition: (id: string) => BASE + '/orders/' + id + '/status',
    bulkProcess:BASE + '/orders/bulk-process',
    export:     BASE + '/orders/export',
    invoice:    (id: string) => BASE + '/orders/' + id + '/invoice',
  },
  inventory: {
    list:      BASE + '/inventory',
    adjust:    BASE + '/inventory/adjust',
    movements: BASE + '/inventory/movements',
    alerts:    BASE + '/inventory/alerts',
    valuation: BASE + '/inventory/valuation',
    export:    BASE + '/inventory/export',
  },
  warehouses: {
    list:   BASE + '/warehouses',
    create: BASE + '/warehouses',
    detail: (id: string) => BASE + '/warehouses/' + id,
    update: (id: string) => BASE + '/warehouses/' + id,
    delete: (id: string) => BASE + '/warehouses/' + id,
    zones:  (id: string) => BASE + '/warehouses/' + id + '/zones',
  },
  deliveries: {
    list:     BASE + '/deliveries',
    detail:   (id: string) => BASE + '/deliveries/' + id,
    update:   (id: string) => BASE + '/deliveries/' + id,
    assign:   BASE + '/deliveries/assign',
    track:    (id: string) => BASE + '/deliveries/' + id + '/track',
    pod:      (id: string) => BASE + '/deliveries/' + id + '/pod',
    earnings: BASE + '/deliveries/earnings',
    tasks:    BASE + '/deliveries/tasks',
  },
  suppliers: {
    list:   BASE + '/suppliers',
    create: BASE + '/suppliers',
    detail: (id: string) => BASE + '/suppliers/' + id,
    update: (id: string) => BASE + '/suppliers/' + id,
    delete: (id: string) => BASE + '/suppliers/' + id,
  },
  purchaseOrders: {
    list:    BASE + '/purchase-orders',
    create:  BASE + '/purchase-orders',
    detail:  (id: string) => BASE + '/purchase-orders/' + id,
    update:  (id: string) => BASE + '/purchase-orders/' + id,
    receive: (id: string) => BASE + '/purchase-orders/' + id + '/receive',
  },
  returns: {
    list:    BASE + '/returns',
    create:  BASE + '/returns',
    detail:  (id: string) => BASE + '/returns/' + id,
    approve: (id: string) => BASE + '/returns/' + id + '/approve',
    reject:  (id: string) => BASE + '/returns/' + id + '/reject',
  },
  notifications: {
    list:        BASE + '/notifications',
    markRead:    (id: string) => BASE + '/notifications/' + id + '/read',
    markAllRead: BASE + '/notifications/read-all',
    delete:      (id: string) => BASE + '/notifications/' + id,
    preferences: BASE + '/notifications/preferences',
  },
  analytics: {
    dashboard:  BASE + '/analytics/dashboard',
    revenue:    BASE + '/analytics/revenue',
    inventory:  BASE + '/analytics/inventory',
    orders:     BASE + '/analytics/orders',
    deliveries: BASE + '/analytics/deliveries',
    export:     BASE + '/analytics/export',
  },
  admin: {
    users:       BASE + '/admin/users',
    userDetail:  (id: string) => BASE + '/admin/users/' + id,
    createUser:  BASE + '/admin/users',
    updateUser:  (id: string) => BASE + '/admin/users/' + id,
    deleteUser:  (id: string) => BASE + '/admin/users/' + id,
    auditLogs:   BASE + '/admin/audit-logs',
    settings:    BASE + '/admin/settings',
    systemHealth:BASE + '/admin/health',
  },
  profile: {
    get:            BASE + '/profile',
    update:         BASE + '/profile',
    changePassword: BASE + '/profile/password',
    uploadAvatar:   BASE + '/profile/avatar',
  },
} as const;
